"""empty message

Revision ID: 19469ef3794b
Revises: 7ce2b238617f
Create Date: 2021-06-30 23:48:52.419220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19469ef3794b'
down_revision = '7ce2b238617f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('name', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'favorite', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='unique')
    op.drop_column('favorite', 'name')
    # ### end Alembic commands ###
